# Docker build task Docker@2
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'gitea_service_connection'
  imageRepository: 'olebrusselsgiteawoodpecker'
  containerRegistry: 'containeregtraining.azurecr.io'
  dockerfilePath: 'Dockerfile.dev'
  tag: '$(Build.gitea)'
  dockerUsername: "mpueyofer"
  dockerPassword: "6rrzAMeVdf49H4"


  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  container: node:16

stages:
- stage: build_run_and_test
  displayName: Build run and test
  jobs:
  - job: build_run_and_test
    displayName: Build run and test
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build 
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Login to Docker
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
        username: $(dockerUsername)
        password: $(dockerPassword)

    - task: Docker@2
      displayName: Run
      inputs: 
        command: run
        container: $(tag)latest
        workingDirectory: '/app'


    

  


