trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_IMAGE_NAME: 'mpueyofer/gitea_woodpecker'
  DOCKER_IMAGE_TAG: 'latest'

stages:
  - stage: Build
    displayName: 'Build Docker Image'
    jobs:
      - job: Build
        displayName: 'Build Docker Image'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'build'
              Dockerfile: 'Dockerfile.dev'
              tags: '${{ variables.DOCKER_IMAGE_NAME }}:${{ variables.DOCKER_IMAGE_TAG }}'
              sudo: true

  - stage: Test
    displayName: 'Run Test Suite'
    jobs:
      - job: Test
        displayName: 'Run Test Suite'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Run Test Suite'
            inputs:
          
              image: '${{ variables.DOCKER_IMAGE_NAME }}:${{ variables.DOCKER_IMAGE_TAG }}'
              sudo: true
              command: 'npm run test'
