# File: azure-pipelines.yml

# Starter pipeline for building and testing a React app with Docker
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Install Docker'
  inputs:
    command: 'docker run -d -p 80:80 docker/getting-started'
    dockerVersion: '19.03.12'

- task: Docker@2
  displayName: 'Build development image'
  inputs:
    command: 'build'
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile.dev'
    tags: 'mpueyofer/gitea_woodpecker'

- task: Docker@2
  displayName: 'Start development container'
  inputs:
    command: 'run'
    containerName: 'gitea_woodpecker'
    imageName: 'mpueyofer/gitea_woodpecker'
    detached: true

- task: Docker@2
  displayName: 'Run tests in development container'
  inputs:
    command: 'run'
    containerName: 'gitea_woodpecker'
    entrypoint: 'npm run test'
